version: '3'

services:
  backend:
    image: ghcr.io/myrenic/docker-example-backend:latest # Ensure to change username to your GitHub username
    ports:
      - "5032:5000"

  frontend:
    image: ghcr.io/myrenic/docker-example-frontend:latest # Ensure to change username to your GitHub username
    ports:
      - "8072:80"
    depends_on:
      - backend